# Open midi file


In [5]:
import mido
import numpy as np
import pygame
import time

In [10]:
def open_midi(file_path):
    mid = mido.MidiFile(file_path)

    notes = []
    for track in mid.tracks:
        absolute_time = 0
        for msg in track:
            absolute_time += msg.time
            if msg.type == "note_on" and msg.velocity > 0:
                notes.append([absolute_time, msg.note, msg.velocity, msg.channel])

    notes_array = np.array(notes, dtype=np.int32)
    return notes_array

In [9]:
def play_midi(file_path):
    pygame.mixer.init()
    pygame.mixer.music.load(file_path)
    pygame.mixer.music.play()

    try:
        while pygame.mixer.music.get_busy():
            time.sleep(1)
    except KeyboardInterrupt:
        pass
    finally:
        pygame.mixer.music.stop()
        pygame.mixer.quit()

In [ ]:
play_midi("unravel.mid")

In [11]:
notes = open_midi("unravel.mid")

print(f"Shape: {notes.shape}")
print(f"Columnas: [tiempo_absoluto, nota, velocidad, canal]")
print(notes[:20])

Shape: (279, 4)
Columnas: [tiempo_absoluto, nota, velocidad, canal]
[[   0   82   80    0]
 [ 480   84   80    0]
 [ 960   82   80    0]
 [1440   82   80    0]
 [1680   79   80    0]
 [2160   84   80    0]
 [2640   82   80    0]
 [3120   81   80    0]
 [3600   79   80    0]
 [4080   79   80    0]
 [4320   77   80    0]
 [5040   77   80    0]
 [5280   75   80    0]
 [5760   77   80    0]
 [6000   74   80    0]
 [7920   74   80    0]
 [8160   74   80    0]
 [8640   74   80    0]
 [8880   74   80    0]
 [9360   84   80    0]]
